// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdVfS_XxvZ49MsjdcdtTn9qtkpF29k1mI',
    appId: '1:324221966918:web:5a49f6301fe9eaa2154847',
    messagingSenderId: '324221966918',
    projectId: 'nuruai-5f50c',
    authDomain: 'nuruai-5f50c.firebaseapp.com',
    storageBucket: 'nuruai-5f50c.firebasestorage.app',
    measurementId: 'G-W8F2L1SJ2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUJug9W9IpD5kBbV8UsrXDQMzRdvHjvZg',
    appId: '1:324221966918:android:e4ca2715627cc383154847',
    messagingSenderId: '324221966918',
    projectId: 'nuruai-5f50c',
    storageBucket: 'nuruai-5f50c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQXJ-Sua6phlXfuhOpE-fULhLyloGkHGg',
    appId: '1:324221966918:ios:52040f1571ae6c47154847',
    messagingSenderId: '324221966918',
    projectId: 'nuruai-5f50c',
    storageBucket: 'nuruai-5f50c.firebasestorage.app',
    iosBundleId: 'com.example.nuruai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQXJ-Sua6phlXfuhOpE-fULhLyloGkHGg',
    appId: '1:324221966918:ios:52040f1571ae6c47154847',
    messagingSenderId: '324221966918',
    projectId: 'nuruai-5f50c',
    storageBucket: 'nuruai-5f50c.firebasestorage.app',
    iosBundleId: 'com.example.nuruai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdVfS_XxvZ49MsjdcdtTn9qtkpF29k1mI',
    appId: '1:324221966918:web:8196bd179ed935af154847',
    messagingSenderId: '324221966918',
    projectId: 'nuruai-5f50c',
    authDomain: 'nuruai-5f50c.firebaseapp.com',
    storageBucket: 'nuruai-5f50c.firebasestorage.app',
    measurementId: 'G-6L00E967M0',
  );
}
